# Generated by Django 4.2.4 on 2023-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_statistics_download_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mirrorserver",
            name="legacy_connection_mode",
            field=models.BooleanField(
                default=False,
                help_text="Disables certain SSH key verification algorithms. We recommend leaving this unchecked "
                "unless something goes wrong during the verification process.",
            ),
        ),
    ]
