# Generated by Django 4.2.7 on 2023-11-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_mirrorserver_legacy_connection_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="x86_type",
            field=models.TextField(
                blank=True,
                help_text="Type of x86 build. Do not set if the codename is not x86!",
                max_length=10,
            ),
        ),
    ]
