# Generated by Django 4.2.7 on 2023-11-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_build_x86_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codename",
                    models.TextField(
                        help_text="Codename of the variant<br>Example: 'vanilla', 'gapps')",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the variant<br>Example: 'Vanilla (no GApps)', 'GApps'",
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
