# Generated by Django 4.2.7 on 2023-11-23 22:54
import ast

from constance import config
from django.db import migrations


def create_variants(apps, _):
    # noinspection PyPep8Naming
    Variant = apps.get_model("core", "Variant")
    try:
        variant_data_from_config = ast.literal_eval(config.SHIPPER_UPLOAD_VARIANTS)
    except AttributeError:
        # We've deprecated and removed this option sometime in the future
        # Just initialize an empty dataset
        return
    new_variant_data = []

    for key in variant_data_from_config:
        new_variant_data.append(
            {"codename": key, "description": variant_data_from_config[key]}
        )

    for variant_data in new_variant_data:
        Variant.objects.create(**variant_data)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_variant"),
    ]

    operations = [migrations.RunPython(create_variants)]
