# Generated by Django 4.2.7 on 2023-11-23 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_variant_from_config"),
    ]

    operations = [
        migrations.RenameField(
            model_name="build",
            old_name="variant",
            new_name="variant_raw",
        ),
    ]
