# Generated by Django 4.2.7 on 2023-11-24 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_variant_build_variant_raw"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.variant",
            ),
        ),
    ]
