# Generated by Django 4.2.7 on 2023-11-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_variant_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.variant"
            ),
        ),
    ]
