# Generated by Django 4.2.7 on 2023-11-24 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_build_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="build",
            name="variant_raw",
        ),
    ]
