# Generated by Django 4.2.7 on 2023-11-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_build_variant_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="codename",
            field=models.TextField(
                help_text="Codename of the variant<br>Example: 'vanilla', 'gapps')",
                max_length=10,
                unique=True,
            ),
        ),
    ]
