# Generated by Django 4.2.7 on 2023-11-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_variant_codename"),
    ]

    operations = [
        migrations.CreateModel(
            name="X86Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codename",
                    models.TextField(
                        help_text="Codename of the x86 type<br>Example: 'GO', 'Bass'",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the x86 text, as seen by users<br> Example: 'GO builds', "
                        "'Bass builds'",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="build",
            name="x86_type",
        ),
    ]
