# Generated by Django 4.2.7 on 2023-11-24 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_x86type_remove_build_x86_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="x86_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.x86type",
            ),
        ),
    ]
