# Generated by Django 4.2.7 on 2024-02-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_build_x86_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Show device on the main downloads page"
            ),
        ),
    ]
