# Generated by Django 5.0.3 on 2024-04-02 20:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_device_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='zip_file',
            field=models.FileField(blank=True, unique=True, upload_to=core.models.Build.get_upload_path, verbose_name='Zip file'),
        ),
    ]
