# Generated by Django 5.0.6 on 2024-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_build_zip_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="note",
            field=models.TextField(
                blank=True, help_text="Notes pertaining to device", max_length=500
            ),
        ),
    ]
