# Generated by Django 5.0.6 on 2024-05-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_device_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="x86_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.x86type",
            ),
        ),
    ]
