# Generated by Django 5.0.7 on 2024-07-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_build_x86_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the feature. Shown to users.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the feature. Shown to users.",
                        max_length=500,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="build",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                help_text="Features of this build.",
                related_name="builds",
                to="core.buildfeature",
            ),
        ),
    ]
