# Generated by Django 4.0.7 on 2022-11-30 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_optimized"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statistics",
            name="device",
        ),
    ]
