# Generated by Django 4.2.3 on 2023-07-14 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_statistics_device"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="photo",
            new_name="photo_url",
        ),
    ]
