# Generated by Django 3.2.3 on 2021-05-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20210517_1142"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="backed_up",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the build has been backed up to Sourceforge, if the option is enabled.",
            ),
        ),
    ]
