# Generated by Django 3.2.3 on 2021-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20210526_0623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mirrorserver",
            name="ssh_host_fingerprint",
            field=models.TextField(
                help_text="SSH host fingerprint. Get this with <code>ssh-keyscan hostname</code>.",
                max_length=1000,
                verbose_name="SSH host fingerprint",
            ),
        ),
        migrations.AlterField(
            model_name="mirrorserver",
            name="ssh_host_fingerprint_type",
            field=models.TextField(
                help_text="SSH host fingerprint type. Get this with <code>ssh-keyscan hostname</code>.<br>Example: ssh-rsa, etc.",
                max_length=20,
                verbose_name="SSH host fingerprint type",
            ),
        ),
    ]
