# Generated by Django 3.2.3 on 2021-05-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20210526_0625"),
    ]

    operations = [
        migrations.AddField(
            model_name="mirrorserver",
            name="download_url_base",
            field=models.TextField(
                blank=True,
                help_text="Base of downloads URL, should a download URL exist.<br>Example: if full URL to download is https://downloads.example.com/R/bullhead/Bliss-v14-bullhead-OFFICIAL-gapps-20200608.zip, then the base URL is https://downloads.example.com/R/",
                max_length=100,
                verbose_name="Download URL base",
            ),
        ),
        migrations.AddField(
            model_name="mirrorserver",
            name="downloadable",
            field=models.BooleanField(
                default=False,
                help_text="Whether downloads from this mirror instance is possible or not. If disabled, this mirror will not be shown to users in the mirror list. Make sure to set the URL base field above if you enable this option!",
            ),
        ),
    ]
