# Generated by Django 3.2.3 on 2021-05-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_mirrorserver_download_url_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="mirrorserver",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the server. This is shown to the users on the mirror page.",
                max_length=100,
            ),
        ),
    ]
