# Generated by Django 3.0.7 on 2020-07-02 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('codename', models.TextField(max_length=50)),
                ('manufacturer', models.TextField(max_length=20)),
                ('cpu', models.TextField(max_length=50)),
                ('gpu', models.TextField(max_length=50)),
                ('memory', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('photo', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('maintainers', models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=500)),
                ('sourceforge_direct_link', models.URLField()),
                ('size', models.IntegerField()),
                ('type', models.TextField(max_length=20)),
                ('version', models.TextField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('release', models.TextField(choices=[('STABLE', 'Stable'), ('BETA', 'Beta'), ('ALPHA', 'Alpha')], default='STABLE', max_length=10)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipper.Variant')),
            ],
        ),
    ]
