# Generated by Django 3.1.2 on 2020-10-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0004_auto_20200806_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='release',
        ),
    ]
