# Generated by Django 3.2.3 on 2021-05-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0010_auto_20210526_0616"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mirrorserver",
            options={
                "verbose_name": "mirror server",
                "verbose_name_plural": "mirror servers",
            },
        ),
    ]
