# Generated by Django 3.2.4 on 2021-06-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0019_alter_mirrorserver_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether this build is enabled or not. Disabled builds will not show up to users, or in the updater API until it is enabled again. Disabled builds are still replicated to mirror servers, so a user downloading from a mirror server may see the build listed.",
            ),
        ),
    ]
