# Generated by Django 3.2.5 on 2021-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0020_build_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='download_count',
            field=models.BigIntegerField(default=0, help_text='Approximate download count'),
        ),
    ]
