# Generated by Django 3.2.5 on 2021-07-10 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0021_build_download_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, primary_key=True, serialize=False
                    ),
                ),
                (
                    "download_count",
                    models.BigIntegerField(
                        default=0, help_text="Download count for this date"
                    ),
                ),
            ],
        ),
    ]
