# Generated by Django 3.2.10 on 2022-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0023_alter_statistics_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="size",
            field=models.BigIntegerField(
                help_text="Size of zip file in bytes<br>Example: 857483855"
            ),
        ),
    ]
