# Generated by Django 3.2.10 on 2022-02-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0024_alter_build_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="mirrored_on",
            field=models.ManyToManyField(
                blank=True,
                help_text="Servers this build is mirrored on. Do NOT edit manually.<br>Incorrectly modifying this field may result in mirror servers showing for a given build, even if the build is not mirrored on said mirror server.",
                related_name="builds",
                to="shipper.MirrorServer",
            ),
        ),
    ]
