# Generated by Django 3.2.10 on 2022-02-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0031_alter_build_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
