# Generated by Django 3.2.10 on 2022-02-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0032_delete_statistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="build",
            name="download_count",
        ),
    ]
