# Generated by Django 3.2.12 on 2022-04-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipper', '0034_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='md5_file',
        ),
    ]
