# Generated by Django 3.2.5 on 2021-07-12 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_change_user_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FakeModel",
        ),
    ]
