# Generated by Django 3.2.5 on 2021-07-12 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_delete_fakemodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
